CREATE TABLE IF NOT EXISTS todos (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(80) NOT NULL
    CHECK (CHAR_LENGTH(BTRIM(title)) BETWEEN 1 AND 80),
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS todos_created_at_id_idx
  ON todos (created_at, id);
